server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: native

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info

sms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from: ${COOLSMS_FROM}
  base-url: ${COOLSMS_BASE_URL:https://api.solapi.com}
  ttl-seconds: ${OTP_TTL_SECONDS:180}
  resend-interval-seconds: ${OTP_RESEND_SECONDS:60}
  max-attempts: ${OTP_MAX_ATTEMPTS:5}
  mock: ${SMS_MOCK:false}
