spring:
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000




server:
  port: 8081

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method      # HTTP Method 순서대로 정렬
    tags-sorter: alpha             # 태그 이름 순으로 정렬
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
