name: backend-ci-cd

on:
  push:
    branches: [ develop, master ]

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/teasan-tiggle/tiggle-core-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew clean bootJar -x test

      - name: Login GHCR (push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Compute tag
        id: meta
        run: echo "tag=$(date +%Y%m%d%H%M)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE }}:latest

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/teasan-tiggle/tiggle-core-api
      TAG: ${{ needs.build-and-push.outputs.tag }}
    steps:
      - name: Deploy on EC2 (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE,TAG 
          script: |
            set -e

            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" -p "${{ secrets.GHCR_TOKEN }}"

            cd /srv/app

            IMAGE_TAG="${TAG:-latest}"
            if [ -f .env ]; then
              if grep -q '^APP_IMAGE=' .env; then
                sed -i "s|^APP_IMAGE=.*|APP_IMAGE=${IMAGE}:${IMAGE_TAG}|" .env
              else
                echo "APP_IMAGE=${IMAGE}:${IMAGE_TAG}" >> .env
              fi
            else
              echo "APP_IMAGE=${IMAGE}:${IMAGE_TAG}" >> .env
            fi

            docker compose pull app || true
            docker compose up -d app
            docker image prune -f
