name: backend-ci-cd

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/Teasan-Tiggle/tiggle-core-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build jar
        run: ./gradlew clean bootJar -x test

      - name: Login GHCR (push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set TAG
        run: echo "TAG=$(date +%Y%m%d%H%M)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}
            ${{ env.IMAGE }}:latest

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" -p "${{ secrets.GHCR_TOKEN }}"

            cd /srv/app

            if [ -f .env ]; then
              sed -i "s|^APP_IMAGE=.*|APP_IMAGE=${{ env.IMAGE }}:${{ env.TAG }}|" .env
            else
              echo "APP_IMAGE=${{ env.IMAGE }}:${{ env.TAG }}" >> .env
            fi

            docker compose pull app || true
            docker compose up -d app
            docker image prune -f
